### PR TITLE
Assertion for passed rules

### PR DESCRIPTION
**Pull request by jacob418**
This PR adds a new assertion to check for rules that didn't fail.

In my use-case i generate a ruleset in a common base-class shared by `post` and `patch` form-request classes. I need to ensure, properties are not `required` in the `patch` request.

```php
public function test_email_is_not_required()
{
    $this->createFormRequest(CreatePostRequest::class)
        ->validate([])
        ->assertPassesRules(['email' => 'required']);
}
``` 

Though the assertion-name can suggest something different, this assertion only checks that the named rule doesn't appear in failures. It doesn't check weather the rule has actually been evaluated - this is intentional. However I was not able to come up with a better name - suggestions welcome.

### CODE REVIEW

**Comment by jcergolj** [comment]
Hey, thanks for this PR. Do you think we should better define or explain what this PR do?

For example, I spent a few minutes trying to understand what this is all about, and I am still not sure if I understand this correctly. Are you here to check if it has been added or not? I do understand the problem with having a required email in a POST request and not having an email required in a PATCH, but then I would image the test code would look like something like this. Instead of `assertPassesRule` having `assertRuleIsMissing` or am I completely wrong with my understanding?

```
public function test_email_is_not_required()
{
    $this->createFormRequest(CreatePostRequest::class)
        ->validate([])
        ->assertRuleIsMissing(['email' => 'required']);
}
```

**Comment by jacob418** [comment]
Hi, sry for the late reply, is was ill. This assertion checks that a certain rule didn't fail, no matter if it was present in the rules definition in the first place. As a more complete example:

```php
abstract class UserDataRequest extends FormRequest {
  // snip...

  public function rules (): array {
    return [
      // snip....
      'email' => [
        'email'
      ],
    ];
  }
}

class UserUpdateRequest extends UserDataRequest {}

class UserCreateRequest extends UserDataRequest {
  public function rules (): array {
    $rules = parent::rules();
    $rules['email'][] = 'required';
    return $rules;
  }
}
```

(1) In my tests I want to ensure that `email` is required in `UserCreateRequest` but not in `UserUpdateRequest`. For the required scenario this is simple with `->assertFails(['email' => 'required'])`. For the not-required scenario this would require me to pass a value that matches all other rules and check the test succeeds. For an email this is simple, but for more complex validations this can get really messy, it opens up the possibility to just pass any value regardless of other errors that might occur and just test, that the tested rule succeeds.

(2) In a scenario with more complex rule-sets it can be tedious to create test cases for each and every combination of valid values just to test, that the validation succeeds. With the `assertPassesRule` approach the validation in general might fail while the developer is enabled to test only one condition at a time, resulting in smaller and simpler (tough more) tests.

I could think of a variation where the `assertPasses` method accepts an optional parameter defining which properties/rules should pass validation. If empty, validation needs to pass completely, when set, validation might fail, but no errors must be raised for the defined attributes/rules.

**Comment by jcergolj** [comment]
Hey, thanks for the response. 
```
 $this->createFormRequest(CreatePostRequest::class)
        ->validate([])
        ->assertPassesRules(['email' => 'required']);
}
```

So, if I am not mistaken, this `assertPassesRules` just checks if the rule 'required' is present for the `email` field or if it checks for the errors, too.

**Comment by jacob418** [comment]
It checks that the request has no error for this `rule` - `attribute` combination. If you aren't using the rule, this will pass. If you are using the rule but you provide a suitable value it will also pass - even if other rules fail.

**Comment by jcergolj** [comment]
Would then a better name be `assertRuleMissing` or `assertNotValidated` or `assertRuleSkipped`?

**Comment by jacob418** [comment]
Its not that the rule is skipped. As I said, the test is that there is no such error. The rule can be evaluated anyway. Its hard for me to come up with a meaningful example, since this is intended for more complex situations which require a lot of context.

The goal of this assertion is to create more dedicated test-cases.

Imagine this set of validation rules:

```php
public function rules(): array
{
  return [
    'param1' => ['required' /* even more rules */],
    'param2' => ['required' /* even more rules */],
    // even more params...
  ];
}
```
Though this is easy enough to test it all at once, in a more complex scenario (imagine nested json ojects with a lot of `required_with`, `prohibits`and `required_without` rules) it would be good to write dedicated tests for `param1`, `param2` and all other params. This would mean that one would have to ensure all params receive valid values in each test, which would be really inconvenient in terms of keeping tests as small as possible. It also would increase maintenance effort on the whole testsuite when changes are introduced to one param. Instead of asserting that validation passed in general it would be better to just pass the param, the test is created for and only verify that validation passes for this param. This principle could get refined to test not only distinct params but also their rules.

You are not entirely wrong, of course this validation passes if the rule/param don't get evaluated in the first place - meaning the rule is missing. Though that's only one way to use this validation.

**Comment by jcergolj** [comment]
Sorry to go back and forth with you like this. Now I think I got it :)

What about `assertSingleRulePasses` just to be more explicit?

**Comment by jacob418** [comment]
No problem :)

It just came to my mind that `assertWithoutFailures(['prop' => ['rule1', 'rule2']])` would be a good name, do you agree?

**Comment by jcergolj** [comment]
Due to the merge conflicts, I created a new branch and new PR and merged the @jacob418 code into the master. Thanks for your contribution @jacob418! Good job

**Pull request closed without merging**
